# Generated by Django 3.2.3 on 2021-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMappings',
            fields=[
                ('actionName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CodeString', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestureString', models.CharField(max_length=5)),
                ('swipe', models.BooleanField()),
                ('direction', models.CharField(max_length=20)),
                ('actionName', models.CharField(max_length=100)),
                ('mode', models.IntegerField()),
                ('appName', models.CharField(max_length=100)),
                ('gestureName', models.CharField(max_length=100)),
            ],
        ),
    ]
