# Generated by Django 3.2.3 on 2021-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandGesturesApp', '0002_alter_userconfiguration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNameMappings',
            fields=[
                ('appName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('originalName', models.CharField(max_length=100)),
            ],
        ),
    ]
