# Generated by Django 3.2.3 on 2021-05-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HandGesturesApp', '0003_appnamemappings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionmappings',
            old_name='CodeString',
            new_name='action',
        ),
    ]
